version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "**/*"
    allow:
      # this enables update on indirect dependencies, which makes
      # dependabot likely work on multi-module repo. 
      # (e.g., if `a/go.mod` depends on `./go.mod`, a direct dependency update
      # on `./go.mod` will also update `a/go.mod`)
      # https://github.com/dependabot/dependabot-core/issues/6678
      - dependency-type: all
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      golang-x:
        patterns:
          - "golang.org/x/*"
      containerd:
        patterns:
          - "github.com/containerd/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10